version: "3.8"
services: 
  db:
    image: {docker-image}
    container_name: "{container name}"
    ports:
      - "3306:3306"
    environment: 
      TZ: Asia/Seoul
    restart: always
    env_file: .env
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
