version: "3.8"
services: 
  db:
    image: {docker-image}
    container_name: "{container name}"
    ports:
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: "{db name}"
      MYSQL_ROOT_PASSWORD: "{db password}"
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - D:/docker/mysql/data:/var/lib/mysql
